// Mocks generated by Mockito 5.4.6 from annotations
// in prepare_with_atlas/test/features/interview_session/application/session_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:prepare_with_atlas/features/interview_session/domain/interview_session.dart'
    as _i2;
import 'package:prepare_with_atlas/features/interview_session/domain/interview_stage.dart'
    as _i6;
import 'package:prepare_with_atlas/features/interview_session/domain/session_repository.dart'
    as _i4;
import 'package:prepare_with_atlas/features/interview_session/domain/stage_note.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeInterviewSession_0 extends _i1.SmartFake
    implements _i2.InterviewSession {
  _FakeInterviewSession_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStageNote_1 extends _i1.SmartFake implements _i3.StageNote {
  _FakeStageNote_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionRepository extends _i1.Mock implements _i4.SessionRepository {
  MockSessionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.InterviewSession> create(_i2.InterviewSession? session) =>
      (super.noSuchMethod(
            Invocation.method(#create, [session]),
            returnValue: _i5.Future<_i2.InterviewSession>.value(
              _FakeInterviewSession_0(
                this,
                Invocation.method(#create, [session]),
              ),
            ),
          )
          as _i5.Future<_i2.InterviewSession>);

  @override
  _i5.Future<_i2.InterviewSession?> getById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i5.Future<_i2.InterviewSession?>.value(),
          )
          as _i5.Future<_i2.InterviewSession?>);

  @override
  _i5.Future<List<_i2.InterviewSession>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i5.Future<List<_i2.InterviewSession>>.value(
              <_i2.InterviewSession>[],
            ),
          )
          as _i5.Future<List<_i2.InterviewSession>>);

  @override
  _i5.Future<void> update(_i2.InterviewSession? session) =>
      (super.noSuchMethod(
            Invocation.method(#update, [session]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> delete(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<List<_i2.InterviewSession>> watchAll() =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, []),
            returnValue: _i5.Stream<List<_i2.InterviewSession>>.empty(),
          )
          as _i5.Stream<List<_i2.InterviewSession>>);

  @override
  _i5.Future<_i3.StageNote> saveStageNote(_i3.StageNote? note) =>
      (super.noSuchMethod(
            Invocation.method(#saveStageNote, [note]),
            returnValue: _i5.Future<_i3.StageNote>.value(
              _FakeStageNote_1(this, Invocation.method(#saveStageNote, [note])),
            ),
          )
          as _i5.Future<_i3.StageNote>);

  @override
  _i5.Future<List<_i3.StageNote>> getStageNotes(int? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#getStageNotes, [sessionId]),
            returnValue: _i5.Future<List<_i3.StageNote>>.value(
              <_i3.StageNote>[],
            ),
          )
          as _i5.Future<List<_i3.StageNote>>);

  @override
  _i5.Future<_i3.StageNote?> getStageNote(
    int? sessionId,
    _i6.InterviewStage? stage,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getStageNote, [sessionId, stage]),
            returnValue: _i5.Future<_i3.StageNote?>.value(),
          )
          as _i5.Future<_i3.StageNote?>);
}
