include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - 'lib/data/local/app_database.g.dart'

linter:
  rules:
    avoid_print: false
