import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:prepare_with_atlas/features/problem_bank/domain/experience_level.dart';

part 'problem.freezed.dart';
part 'problem.g.dart';

/// Immutable domain model representing a system-design interview problem.
///
/// Metadata fields ([difficulty], [category], [tags]) exist only to support
/// AI evaluation (Spec 06) and section grouping. They must NEVER be shown
/// directly in the Problem Bank UI.
@freezed
abstract class Problem with _$Problem {
  /// Creates a [Problem].
  const factory Problem({
    /// Unique identifier assigned by the database.
    required int id,

    /// Short title of the problem — the ONLY field shown in the Problem Bank.
    required String title,

    /// Full problem statement shown at session start only.
    required String description,

    /// Raw difficulty string: 'easy' | 'medium' | 'hard'. Metadata only.
    required String difficulty,

    /// High-level category. Metadata only.
    required String category,

    /// Timestamp when the problem was stored locally.
    required DateTime createdAt,

    /// Optional keyword tags. Metadata only.
    @Default([]) List<String> tags,

    /// Model answer shown only after AI evaluation. May be null.
    String? referenceSolution,

    /// Whether this problem was hand-curated by the Atlas team.
    @Default(true) bool isCurated,

    /// Whether this problem was generated by the AI (Spec 05).
    @Default(false) bool isAiGenerated,
  }) = _Problem;

  /// Deserialises a [Problem] from a JSON map.
  factory Problem.fromJson(Map<String, dynamic> json) =>
      _$ProblemFromJson(json);

  const Problem._();

  /// Returns the [ExperienceLevel] for this problem's difficulty.
  ExperienceLevel get experienceLevel =>
      ExperienceLevel.fromDifficulty(difficulty);
}
