// Mocks generated by Mockito 5.4.6 from annotations
// in prepare_with_atlas/test/features/ai_provider/application/ai_provider_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:prepare_with_atlas/features/ai_provider/domain/ai_completion_result.dart'
    as _i2;
import 'package:prepare_with_atlas/features/ai_provider/domain/ai_message.dart'
    as _i8;
import 'package:prepare_with_atlas/features/ai_provider/domain/ai_provider.dart'
    as _i6;
import 'package:prepare_with_atlas/features/ai_provider/domain/ai_provider_config.dart'
    as _i5;
import 'package:prepare_with_atlas/features/ai_provider/domain/ai_provider_config_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAiCompletionResult_0 extends _i1.SmartFake
    implements _i2.AiCompletionResult {
  _FakeAiCompletionResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AiProviderConfigRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiProviderConfigRepository extends _i1.Mock
    implements _i3.AiProviderConfigRepository {
  MockAiProviderConfigRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> save(_i5.AiProviderConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#save, [config]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.AiProviderConfig?> getActive() =>
      (super.noSuchMethod(
            Invocation.method(#getActive, []),
            returnValue: _i4.Future<_i5.AiProviderConfig?>.value(),
          )
          as _i4.Future<_i5.AiProviderConfig?>);

  @override
  _i4.Future<List<_i5.AiProviderConfig>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i4.Future<List<_i5.AiProviderConfig>>.value(
              <_i5.AiProviderConfig>[],
            ),
          )
          as _i4.Future<List<_i5.AiProviderConfig>>);

  @override
  _i4.Future<void> setActive(String? providerName) =>
      (super.noSuchMethod(
            Invocation.method(#setActive, [providerName]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> delete(String? providerName) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [providerName]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [AiProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiProvider extends _i1.Mock implements _i6.AiProvider {
  MockAiProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get providerName =>
      (super.noSuchMethod(
            Invocation.getter(#providerName),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#providerName),
            ),
          )
          as String);

  @override
  String get currentModel =>
      (super.noSuchMethod(
            Invocation.getter(#currentModel),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#currentModel),
            ),
          )
          as String);

  @override
  bool get supportsVision =>
      (super.noSuchMethod(
            Invocation.getter(#supportsVision),
            returnValue: false,
          )
          as bool);

  @override
  _i4.Future<_i2.AiCompletionResult> complete(List<_i8.AiMessage>? messages) =>
      (super.noSuchMethod(
            Invocation.method(#complete, [messages]),
            returnValue: _i4.Future<_i2.AiCompletionResult>.value(
              _FakeAiCompletionResult_0(
                this,
                Invocation.method(#complete, [messages]),
              ),
            ),
          )
          as _i4.Future<_i2.AiCompletionResult>);

  @override
  _i4.Future<bool> testConnection() =>
      (super.noSuchMethod(
            Invocation.method(#testConnection, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
