// Mocks generated by Mockito 5.4.6 from annotations
// in prepare_with_atlas/test/presentation/shell/app_shell_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:prepare_with_atlas/features/settings/data/preferences_repository.dart'
    as _i3;
import 'package:prepare_with_atlas/features/settings/domain/app_preferences.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppPreferences_0 extends _i1.SmartFake
    implements _i2.AppPreferences {
  _FakeAppPreferences_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PreferencesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreferencesRepository extends _i1.Mock
    implements _i3.PreferencesRepository {
  MockPreferencesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AppPreferences> load() =>
      (super.noSuchMethod(
            Invocation.method(#load, []),
            returnValue: _i4.Future<_i2.AppPreferences>.value(
              _FakeAppPreferences_0(this, Invocation.method(#load, [])),
            ),
          )
          as _i4.Future<_i2.AppPreferences>);

  @override
  _i4.Future<void> save(_i2.AppPreferences? prefs) =>
      (super.noSuchMethod(
            Invocation.method(#save, [prefs]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
