// Mocks generated by Mockito 5.4.6 from annotations
// in prepare_with_atlas/test/features/history/application/comparison_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:prepare_with_atlas/features/evaluation/domain/evaluation_repository.dart'
    as _i2;
import 'package:prepare_with_atlas/features/evaluation/domain/evaluation_result.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [EvaluationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEvaluationRepository extends _i1.Mock
    implements _i2.EvaluationRepository {
  MockEvaluationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> save(_i4.EvaluationResult? evaluation) =>
      (super.noSuchMethod(
            Invocation.method(#save, [evaluation]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.EvaluationResult?> getBySessionId(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#getBySessionId, [sessionId]),
            returnValue: _i3.Future<_i4.EvaluationResult?>.value(),
          )
          as _i3.Future<_i4.EvaluationResult?>);

  @override
  _i3.Future<List<_i4.EvaluationResult>> getAllBySessionId(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#getAllBySessionId, [sessionId]),
            returnValue: _i3.Future<List<_i4.EvaluationResult>>.value(
              <_i4.EvaluationResult>[],
            ),
          )
          as _i3.Future<List<_i4.EvaluationResult>>);

  @override
  _i3.Future<List<_i4.EvaluationResult>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i3.Future<List<_i4.EvaluationResult>>.value(
              <_i4.EvaluationResult>[],
            ),
          )
          as _i3.Future<List<_i4.EvaluationResult>>);

  @override
  _i3.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
